# This query returns the number of schema:Person instances with a Library of Congress country code URI for schema:nationality representing Belgium

prefix countries: <http://id.loc.gov/vocabulary/countries/>
prefix schema: <http://schema.org/>

SELECT (COUNT(?person) as ?count)
WHERE {
  ?person a schema:Person ;
    schema:nationality countries:be .
}
