prefix dcterms: <http://purl.org/dc/terms/>
prefix fabio: <http://purl.org/spar/fabio/>

SELECT DISTINCT ?manifestationID ?clusterID
WHERE {
  graph <http://beltrans-works> { 
    ?c a fabio:Work ;
       dcterms:identifier ?clusterID ;
       fabio:hasManifestation ?m .
  } 
        
  graph <http://beltrans-manifestations> { ?m dcterms:identifier ?manifestationID . }
  
}
