prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix schema: <http://schema.org/>
prefix up: <http://users.ugent.be/~tdenies/up/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix btid: <http://kbr.be/id/data/>
prefix btm: <http://kbr.be/ns/beltrans/model#>

DELETE {
  graph <http://kbr-syracuse> { ?translationActivity prov:used ?original . }
}
WHERE {
  graph <http://kbr-syracuse> { 
    ?translationActivity a prov:Activity ;
                         up:assertionConfidence ?similarity ;
  						 prov:generated ?translation ;
  						 prov:used ?original ;
                         prov:used ?originalLimitedInfo .
  }
        
  graph <http://kbr-originals> { ?original dcterms:identifier ?originalID . }
  graph <http://kbr-originals> { ?originalLimitedInfo dcterms:identifier ?originalLimitedInfoID . }
  FILTER(!STRSTARTS(?originalID, "source"))
  FILTER(STRSTARTS(?originalLimitedInfoID, "source"))
        
  FILTER NOT EXISTS { ?translationActivity btm:verifiedBy btid:overlappingContributors . }
  
}
