PREFIX bibo: <http://purl.org/ontology/bibo/>

SELECT ?manifestation ?isbn10
WHERE {
  graph <http://bnf-publications> { ?manifestation bibo:isbn10 ?isbn10 . } 
  FILTER (!regex(?isbn10, "-", "i"))
}
