prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix schema: <http://schema.org/>
prefix bibo: <http://purl.org/ontology/bibo/>
prefix fabio: <http://purl.org/spar/fabio/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX btm: <http://kbr.be/ns/beltrans/model#>
PREFIX btid: <http://kbr.be/id/data/> 
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX btisni: <http://kbr.be/isni/>
PREFIX mads: <http://www.loc.gov/mads/rdf/v1#>
PREFIX up: <http://users.ugent.be/~tdenies/up/>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/> 
PREFIX rdagroup1elements: <http://rdvocab.info/Elements/>
PREFIX rdagroup2elements: <http://rdvocab.info/ElementsGr2/>


SELECT DISTINCT ?beltransID ?orgCity ?orgCountryLabel
WHERE {

  graph <http://beltrans-contributors> {
    ?org a schema:Organization ;
         dcterms:identifier ?beltransID ;
         schema:address ?orgAddress .

    ?orgAddress a schema:PostalAddress .
  }
  
  OPTIONAL { graph <http://beltrans-contributors> { ?orgAddress schema:addressLocality ?orgCity . } }
  OPTIONAL { 
    graph <http://beltrans-contributors> { ?orgAddress schema:addressCountry ?orgCountryCode . } 

    graph <http://master-data> { ?orgCountryCode mads:authoritativeLabel ?orgCountryLabel . }
    FILTER (lang(?orgCountryLabel) = 'en')
  }
  

         
}
