prefix schema: <http://schema.org/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix fabio: <http://purl.org/spar/fabio/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
prefix btid: <http://kbr.be/id/data/>


SELECT ?clusterID ?oldestMID ?numManifestations ?numSameAge ?title
WHERE {

  graph <http://beltrans-works> { ?cluster dcterms:identifier ?clusterID . }
  #OPTIONAL { 
  #  graph <http://beltrans-works> { ?cluster schema:about ?genre . } 
  #  graph <http://master-data> { ?genre skos:prefLabel ?genreLabel . }
  #  FILTER(lang(?genreLabel) = 'en')
  #}

  graph <http://beltrans-manifestations> { 
    ?oldestM schema:name ?title ;
             dcterms:identifier ?oldestMID ;
             schema:datePublished ?oldestYearOfPublication .
  }

  # intermediate query to select one of possibly multiple oldest manifestations
  #
  {
    SELECT ?cluster (SAMPLE(?m) as ?oldestM) ?numManifestations (COUNT(?m) as ?numSameAge)
    WHERE {
      graph <http://beltrans-manifestations> {
        ?m schema:datePublished ?minDate
      }
      graph <http://beltrans-works> {
        ?cluster fabio:hasManifestation ?m .
      }
            
      # inner query to select the year of the oldest manifestation per cluster
      #
      {
        SELECT ?cluster (MIN(?pubDate) as ?minDate) (COUNT(?m) as ?numManifestations)
        WHERE {
          graph <http://beltrans-manifestations> {
            ?m a schema:CreativeWork ;
                 schema:isPartOf btid:beltransCorpus ;
                 schema:datePublished ?pubDate .

          }
          graph <http://beltrans-works> {
            ?cluster fabio:hasManifestation ?m .
          }
        }
        GROUP BY ?cluster ?numManifestations
      } # end innermost query to find oldest manifestations
    }
    GROUP BY ?cluster ?numManifestations ?numSameAge
  } # end middle filter query
}
