PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX isni: <http://isni.org/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdagroup2elements: <http://rdvocab.info/ElementsGr2/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>


INSERT {

  GRAPH <http://data.kbr.be/graphs/staging/authors> {
    ?person a schema:Person ;
      schema:familyName    ?familyName ;
      schema:givenName     ?firstName ;
#      schema:gender        ?gender ;
      schema:nationality   ?nationality ;
      schema:knowsLanguage ?language ;
      bf:identifiedBy      ?isni ;
      owl:sameAs ?sameSKOS ;
      owl:sameAs ?sameOWL .
  }
}
WHERE {
 
  SERVICE <http://localhost:8090/bigdata/namespaces/kb-authors-nta>
  {

    ?person a schema:Person .
  
    OPTIONAL { ?person rdfs:label ?label .}
    OPTIONAL { ?person schema:familyName ?familyName .}
    OPTIONAL { ?person schema:givenname ?givenname .}
    OPTIONAL { ?person schema:alternateName ?altName .}
    OPTIONAL { ?person schema:nationality ?nationality .}
    OPTIONAL { ?person schema:birthDate ?birthDate .}
    OPTIONAL { ?person schema:deathDate ?deathDate .} 
    OPTIONAL { ?person schema:sameAs ?sameAsSchema .}
   
  }  
}
