prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix schema: <http://schema.org/>
prefix bibo: <http://purl.org/ontology/bibo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX btm: <http://kbr.be/ns/beltrans/model#>
PREFIX btid: <http://kbr.be/id/data/> 
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX btisni: <http://kbr.be/isni/>
PREFIX mads: <http://www.loc.gov/mads/rdf/v1#>
PREFIX up: <http://users.ugent.be/~tdenies/up/>

  SELECT DISTINCT
  
    (?kbrSourceManifestationID AS ?sourceTextKBRIdentifier)
    (group_concat(distinct ?kbrSourceLangLabel;SEPARATOR=';') AS ?sourceTextLanguage)
    (group_concat(distinct ?kbrTargetLangLabel;SEPARATOR=';') AS ?targetTextLanguage)
    (?kbrSourceManifestationISBN13 AS ?sourceTextISBN)
    (group_concat(distinct ?kbrSourceManifestationTitle;SEPARATOR=';') AS ?sourceTextTitle)
    (COUNT(?manifestation) AS ?numberTranslations)
#    (group_concat(distinct ?manifestationID;SEPARATOR=';') AS ?targetTextKBRIdentifier)
#    (group_concat(distinct ?manifestationTitle;SEPARATOR=';') AS ?targetTextTitle)

  FROM <http://kbr-syracuse>
  FROM <http://isni-sru>
  FROM <http://kbr-belgians>
  FROM <http://isni-rdf>
  FROM <http://master-data>
  FROM <http://kbr-linked-authorities>
  WHERE {

    graph <http://kbr-syracuse> {
      ?manifestation schema:translationOfWork ?manifestationSource .

      ?manifestationSource schema:inLanguage ?kbrSourceLang ;
                           dcterms:identifier ?kbrSourceManifestationID ;
                           schema:name ?kbrSourceManifestationTitle .
    }
    
    OPTIONAL { graph <http://kbr-syracuse> { ?manifestationSource bibo:isbn13 ?kbrSourceManifestationISBN13 . } }

    OPTIONAL {
      graph <http://master-data> { ?kbrSourceLang mads:authoritativeLabel ?kbrSourceLangLabel . }
      FILTER (lang(?kbrSourceLangLabel) = 'en')
    }

   
    #
    # TARGET LANGUAGE
    #
    OPTIONAL { 
      graph <http://kbr-syracuse> { ?manifestation schema:inLanguage ?kbrTargetLang . } 

      # within the optional language check optionally for an English label of it (it should exist though)
      OPTIONAL {
        graph <http://master-data> { ?kbrTargetLang mads:authoritativeLabel ?kbrTargetLangLabel . }
        FILTER (lang(?kbrTargetLangLabel) = 'en')
      }
    } 


    #
    # ALL THE CONTENT BEGINNING FROM HERE QUERIES CONTRIBUTOR INFORMATION
    # AND IS ALSO USED FOR FILTERING BASED ON BELGIAN NATIONALITY
    #

    # ---------------------------------------------------------------------------
    #
    # (1) AUTHOR
    #
    # if there is an author we optionally check this data source and other data sources for other optional attributes of the author
    #
    OPTIONAL { 
      graph <http://kbr-syracuse> { ?manifestation schema:author ?kbrAuthor . } 

      # within this optional author check optionally for Belgians from KBR (it could be the author from kbr-syracuse is not in kbr-belgians
      OPTIONAL {
        graph <http://kbr-belgians> { 
          # There is always a nationality for this dataset, thus not optional
          ?kbrAuthor a schema:Person ;
                     dcterms:identifier ?kbrAuthorID ;
                     schema:nationality ?kbrAuthorNationality . 
        }

        # within this optional nationality check optionally for an English label in the master data
        OPTIONAL {
          graph <http://master-data> { ?kbrAuthorNationality mads:authoritativeLabel ?kbrAuthorNationalityLabel . }
          FILTER (lang(?kbrAuthorNationalityLabel) = 'en')
        }
      }
    }

    # ---------------------------------------------------------------------------
    #
    # (2) TRANSLATOR
    #
    # if there is a translator we optionally check this data source and other data sources for other optional attributes of the translator
    #
    OPTIONAL { 

      graph <http://kbr-syracuse> { ?manifestation schema:translator ?kbrTranslator . } 

      # within this optional translator check optionally for Belgians from KBR (it could be the translator from kbr-syracuse is not in kbr-belgians
      OPTIONAL {
        graph <http://kbr-belgians> { 
          # There is always a nationality for this dataset, thus not optional
          ?kbrTranslator a schema:Person ;
                         dcterms:identifier ?kbrTranslatorID ;
                         schema:nationality ?kbrTranslatorNationality . 
        }

        # within this optional nationality check optionally for an English label in the master data
        OPTIONAL {
          graph <http://master-data> { ?kbrTranslatorNationality mads:authoritativeLabel ?kbrTranslatorNationalityLabel . }
          FILTER (lang(?kbrTranslatorNationalityLabel) = 'en')
        }
      }
    }


    # ---------------------------------------------------------------------------
    #
    # (3) PUBLISHER
    #
    # if there is a publisher we optionally check this data source and other data sources for other optional attributes of the publisher
    #
    OPTIONAL { 

      graph <http://kbr-syracuse> { ?manifestation schema:publisher ?kbrPublisher . } 

      OPTIONAL {
        graph <http://kbr-syracuse> { 

        ?publisherAssociation a prov:Association ;
                                prov:agent ?kbrPublisher ;
                                prov:hadRole btid:role_pbl .

        ?publisherTranslationActivity a prov:Activity ;
                  prov:qualifiedAssociation ?publisherAssociation ;
                  prov:generated ?manifestation .
        }

        OPTIONAL {
          graph <http://kbr-linked-authorities> { ?kbrPublisher dcterms:identifier ?kbrPublisherID . }
        }

        OPTIONAL {
          graph <http://kbr-syracuse> { ?publisherAssociation up:assertionType ?publisherUncertainty . }
        }
      }
    }

    # ---------------------------------------------------------------------------
    #
    # (4) ILLUSTRATOR
    #
    # if there is a illustrator we optionally check this data source and other data sources for other optional attributes of the illustrator
    #
    OPTIONAL { 

      graph <http://kbr-syracuse> { 
        ?illustratorAssociation a prov:Association ;
                                prov:agent ?kbrIllustrator ;
                                prov:hadRole btid:role_ill .

        ?activity a prov:Activity ;
                  prov:qualifiedAssociation ?illustratorAssociation ;
                  prov:generated ?manifestation .
      } 

      # within this optional illustrator check optionally for Belgians from KBR (it could be the illustrator from kbr-syracuse is not in kbr-belgians
      OPTIONAL {
        graph <http://kbr-belgians> { 
          # There is always a nationality for this dataset, thus not optional
          ?kbrIllustrator a schema:Person ;
                          dcterms:identifier ?kbrIllustratorID ;
                          schema:nationality ?kbrIllustratorNationality . 
        }

        # within this optional nationality check optionally for an English label in the master data
        OPTIONAL {
          graph <http://master-data> { ?kbrIllustratorNationality mads:authoritativeLabel ?kbrIllustratorNationalityLabel . }
          FILTER (lang(?kbrIllustratorNationalityLabel) = 'en')
        }
      }


    }

    # ---------------------------------------------------------------------------
    #
    # (5) SCENARIST
    #
    # if there is a scenarist we optionally check this data source and other data sources for other optional attributes of the scenarist
    #
    OPTIONAL { 

      graph <http://kbr-syracuse> { 
        ?scenaristAssociation a prov:Association ;
                                prov:agent ?kbrScenarist ;
                                prov:hadRole btid:role_sce .

        ?activity a prov:Activity ;
                  prov:qualifiedAssociation ?scenaristAssociation ;
                  prov:generated ?manifestation .
      } 

      # within this optional scenarist check optionally for Belgians from KBR (it could be the scenarist from kbr-syracuse is not in kbr-belgians
      OPTIONAL {
        graph <http://kbr-belgians> { 
          # There is always a nationality for this dataset, thus not optional
          ?kbrScenarist a schema:Person ;
                        dcterms:identifier ?kbrScenaristID ;
                        schema:nationality ?kbrScenaristNationality . 
        }

        # within this optional nationality check optionally for an English label in the master data
        OPTIONAL {
          graph <http://master-data> { ?kbrScenaristNationality mads:authoritativeLabel ?kbrScenaristNationalityLabel . }
          FILTER (lang(?kbrScenaristNationalityLabel) = 'en')
        }
      }


    }


   FILTER(
     ( !bound(?kbrAuthorNationalityLabel) || str(?kbrAuthorNationalityLabel) = 'Belgium') ||
     ( !bound(?kbrIllustratorNationalityLabel) || str(?kbrIllustratorNationalityLabel) = 'Belgium') ||
     ( !bound(?kbrScenaristNationalityLabel) || str(?kbrScenaristNationalityLabel) = 'Belgium') )

}
GROUP BY ?kbrSourceManifestationID ?kbrSourceManifestationISBN13
ORDER BY DESC(?numberTranslations)
